	<?php
	if(strtoupper($_SERVER['SERVER_NAME'])!='LOCALHOST' && strtoupper($_SERVER['SERVER_NAME'])!='127.0.0.1'){echo 'Not valid Domain';exit;};
	include_once('../config/funcs.php');
	include_once('../config/conn.php');
	exe("DROP TABLE IF EXISTS FCPS");
	exe("DROP TABLE IF EXISTS USUS");
	exe("DROP TABLE IF EXISTS USUS_PERS");
	exe("DROP TABLE IF EXISTS USUS_ACSS");
	exe("DROP TABLE IF EXISTS EMPS");
	exe("DROP TABLE IF EXISTS PRZS");
	exe("DROP TABLE IF EXISTS ESTS");
	exe("DROP TABLE IF EXISTS MDLS");
	exe("DROP TABLE IF EXISTS FCVS");
	exe("DROP TABLE IF EXISTS FCVS_DETS");
	exe("DROP TABLE IF EXISTS PAGS");
	exe("DROP TABLE IF EXISTS PAGS_DETS");
	exe("DROP TABLE IF EXISTS MENUES");
	exe("DROP TABLE IF EXISTS ARTS");
	exe("DROP TABLE IF EXISTS IMPS");
	exe("DROP TABLE IF EXISTS PAISES");
	exe("DROP TABLE IF EXISTS REGS_FISS");
	exe("DROP TABLE IF EXISTS FONS");
	exe("DROP TABLE IF EXISTS FONS_MOTS");
	exe("DROP TABLE IF EXISTS SESS");
	exe("DROP TABLE IF EXISTS ERRORES");
	exe("DROP TABLE IF EXISTS CS_PROS_SRVS");
	exe("DROP TABLE IF EXISTS CS_UNIS_MEDS");
	exe("DROP TABLE IF EXISTS CS_REGS_FISS");
	exe("DROP TABLE IF EXISTS CS_IMPS");
	exe("DROP TABLE IF EXISTS CS_FORS_PAGS");
	
	$SQL="CREATE TABLE FCPS (idFcp INT AUTO_INCREMENT NOT NULL PRIMARY KEY,idUsu INT default 0,idMdl  INT default 0,codigo CHAR (20) default '-',nom CHAR (250) default '-',ape CHAR (250) default '-',fcp CHAR (250) default '-',rso CHAR (250) default '-',rfc CHAR (20) default '-',email CHAR (150) default '-',idRegFis CHAR (10) default '-',regFis CHAR (100) default '-',idFon INT default 0,fon CHAR (100) default '-',tel CHAR (100) default '-',fisDom CHAR (100) default '-',fisDomNro CHAR (100) default '-',fisDomInt CHAR (100) default '-',fisDomCodPos CHAR (100) default '-',fisDomCol CHAR (100) default '-',fisDomMun CHAR (100) default '-',fisDomCiu CHAR (100) default '-',fisDomIdPrz INT default 0,fisDomPrz CHAR (100) default '-',fisDomIdPais INT default 0,fisDomPais CHAR (100) default '-',envDom CHAR (100";
	$SQL.= ") default '-',envDomNro CHAR (100) default '-',envDomInt CHAR (100) default '-',envDomCodPos CHAR (100) default '-',envDomCol CHAR (100) default '-',envDomCiu CHAR (100) default '-',envDomMun CHAR (100) default '-',envDomIdPrz INT default 0,envDomPrz CHAR (100) default '-',envDomIdPais INT default 0,envDomPais CHAR (100) default '-',baja INT default 0) ENGINE = MYISAM";
	exe($SQL);
	exe("CREATE TABLE USUS (idUsu INT AUTO_INCREMENT NOT NULL PRIMARY KEY,nom CHAR (50) default '-',ape CHAR (50) default '-',usu CHAR (150) default '-',pass CHAR (20) default '-',img CHAR (250) default '-',email CHAR (100) default '-',tel CHAR (50) default '-',role CHAR (11) default '-',metodo CHAR (50) default '-',baja INT default 0) ENGINE = MYISAM");
	exe("CREATE TABLE USUS_PERS (ID_USU_PER INT AUTO_INCREMENT NOT NULL PRIMARY KEY,USU_PER CHAR (20) default '-',BAJA TINYINT default 0) ENGINE = MYISAM");
	exe("CREATE TABLE USUS_ACSS (ID_USU_ACS INT AUTO_INCREMENT NOT NULL PRIMARY KEY,ID_USU CHAR (15) default '-',ID_MNU_REG INT default 0,ID_USU_PER INT default 0) ENGINE = MYISAM");
	$SQL="CREATE TABLE EMPS (idEmp INT AUTO_INCREMENT NOT NULL PRIMARY KEY,idUsu INT default 0,emp CHAR (100) default '-',rso CHAR (100) default '-',rfc CHAR (20) default '-',idRegFis CHAR (10) default '-',regFis CHAR (100) default '-',certificado CHAR (50) default '-',llave CHAR (50) default '-',cerPas CHAR (50) default '-',logo CHAR (50) default '-',tel1 CHAR (20) default '-',tel2 CHAR (20) default '-',email CHAR (100) default '-',fisDom CHAR (50) default '-',fisDomNro CHAR (100) default '-',fisDomInt CHAR (100) default '-',fisDomCodPos CHAR (100) default '-',fisDomCol CHAR (100) default '-',fisDomDel CHAR (100) default '-',fisDomCiu CHAR (100) default '-',fisDomMun CHAR (100) default '-',fisDomIdPrz INT default 0,fisDomPrz CHAR (100) default '-',fisDomIdPais INT default 0,fisDomPais CHAR (100) de";
	$SQL.= "fault '-',baja TINYINT default 0) ENGINE = MYISAM";
	exe($SQL);
	exe("CREATE TABLE PRZS (idPrz INT AUTO_INCREMENT NOT NULL PRIMARY KEY,codigo CHAR (15) default '-',prz CHAR (50) default '-',baja TINYINT default 0) ENGINE = MYISAM");
	exe("CREATE TABLE ESTS (idEst INT AUTO_INCREMENT NOT NULL PRIMARY KEY,codigo CHAR (15) default '-',est CHAR (50) default '-',sysCod CHAR (25) default '-',baja TINYINT default 0) ENGINE = MYISAM");
	exe("CREATE TABLE MDLS (ID_MDL INT AUTO_INCREMENT NOT NULL PRIMARY KEY,CODIGO CHAR (15) default '-',MDL CHAR (50) default '-') ENGINE = MYISAM");
	exe("CREATE TABLE FCVS (idFcv INT AUTO_INCREMENT NOT NULL PRIMARY KEY,idUsu INT default 0,idEmp INT default 0,idFcp INT default 0,idMdl INT default 0,idEst INT default 0,punto CHAR (5) default '-',fcpJSON TEXT,letra CHAR (5) default '-',numero CHAR (10) default '-',fecEmi DATETIME,fecVto DATETIME,idMon INT default 0,monCot DECIMAL(11, 4) default 0,subTotal DECIMAL(11, 4) default 0,total DECIMAL(11, 4) default 0,impTotal DECIMAL(11, 4) default 0,saldo DECIMAL(11, 4) default 0,pagoParcialidad INT default 0,obs TEXT,uuid CHAR (100) default '-',bajaFec DATETIME,baja TINYINT default 0) ENGINE = MYISAM");
	exe("CREATE TABLE FCVS_DETS (idFcvDet INT AUTO_INCREMENT NOT NULL PRIMARY KEY,idFcv INT default 0,idArt INT default 0,art TEXT,cantidad DECIMAL(11, 4) default 0,costo DECIMAL(11, 4) default 0,precio DECIMAL(11, 4) default 0,precioManual DECIMAL(11, 4) default 0,importe DECIMAL(11, 4) default 0,idImp INT default 0,imp CHAR (30) default '-',impTotal DECIMAL(11, 4) default 0,impTasa DECIMAL(11, 4) default 0) ENGINE = MYISAM");
	exe("CREATE TABLE PAGS (idPag INT AUTO_INCREMENT NOT NULL PRIMARY KEY,idUsu INT default 0,idEmp INT default 0,idFcp INT default 0,idMdl INT default 0,idEst INT default 0,idCsForPag CHAR (15) default '-',fcpJSON TEXT,letra CHAR (5) default '-',numero CHAR (10) default '-',fecEmi DATETIME,fecPag DATETIME,idMon INT default 0,monCot DECIMAL(11, 4) default 0,total DECIMAL(11, 4) default 0,obs TEXT,uuid CHAR (100) default '-',bajaFec DATETIME,baja TINYINT default 0) ENGINE = MYISAM");
	exe("CREATE TABLE PAGS_DETS (idPagDet INT AUTO_INCREMENT NOT NULL PRIMARY KEY,idPag INT default 0,idFcv INT default 0,FcvJSON TEXT,total DECIMAL(11, 4) default 0,saldo DECIMAL(11, 4) default 0,parcialidad DECIMAL(11, 4) default 0) ENGINE = MYISAM");
	exe("CREATE TABLE MENUES (ID_MNU INT AUTO_INCREMENT NOT NULL PRIMARY KEY,ID_MNU_REG INT default 0,NIVEL INT default 0,ID_MNU_SUP INT default 0,MNU CHAR (50) default '-',MDL CHAR (20) default '-',MNU_RUT CHAR (255) default '-',MNU_ARC CHAR (50) default '-',VIS_RUT CHAR (50) default '-',VIS_ICO CHAR (50) default '-',ACC INT default 0) ENGINE = MYISAM");
	exe("CREATE TABLE ARTS (idArt INT AUTO_INCREMENT NOT NULL PRIMARY KEY,idUsu INT default 0,art CHAR (100) default '-',codigo CHAR (20) default '-',costo DECIMAL(11, 4) default 0,precio DECIMAL(11, 4) default 0,idCsProSrv CHAR (15) default '-',csProSrv CHAR (100) default '-',idImp CHAR (11) default '-',imp CHAR (50) default '-',idMdl INT default 0,impTasa DECIMAL(11, 4) default 0,idUniMed CHAR (11) default '-',uniMed CHAR (11) default '-',baja INT default 0) ENGINE = MYISAM");
	exe("CREATE TABLE IMPS (idImp INT AUTO_INCREMENT NOT NULL PRIMARY KEY,codigo CHAR (20) default '-',imp CHAR (50) default '-',tipo CHAR (10) default '-',idCsImp CHAR (10) default '-',baja INT default 0) ENGINE = MYISAM");
	exe("CREATE TABLE PAISES (idPais INT AUTO_INCREMENT NOT NULL PRIMARY KEY,codigo CHAR (20) default '-',pais CHAR (50) default '-') ENGINE = MYISAM");
	exe("CREATE TABLE REGS_FISS (ID_REG_FIS INT AUTO_INCREMENT NOT NULL PRIMARY KEY,REG_FIS CHAR (50) default '-',ID_CS_REG_FIS CHAR (15) default '-',BAJA INT default 0) ENGINE = MYISAM");
	exe("CREATE TABLE FONS (idFon INT AUTO_INCREMENT NOT NULL PRIMARY KEY,idCsForPag CHAR (15) default '-',idMdl INT default 0,codigo INT default 0,fon CHAR (100) default '-',idMon CHAR (10) default '-',baja INT default 0) ENGINE = MYISAM");
	exe("CREATE TABLE FONS_MOTS (idFonMot INT AUTO_INCREMENT NOT NULL PRIMARY KEY,idFon INT default 0,fonMot CHAR (50) default '-',baja INT default 0) ENGINE = MYISAM");
	exe("CREATE TABLE SESS (ID_SES INT AUTO_INCREMENT NOT NULL PRIMARY KEY,OTC_KEY CHAR (100) default '-',ID_USU INT default 0,EQUIPO CHAR (250) default '-',IP CHAR (30) default '-',DATA CHAR (250) default '-',FECHA DATETIME,ESTADO INT default 0) ENGINE = MYISAM");
	exe("CREATE TABLE ERRORES (idError INT AUTO_INCREMENT NOT NULL PRIMARY KEY,idUsu INT default 0,fecha DATETIME,error TEXT,data TEXT) ENGINE = MYISAM");
	exe("CREATE TABLE CS_PROS_SRVS (idCsProSrv CHAR (15) NOT NULL PRIMARY KEY,csProSrv CHAR (250) default '-') ENGINE = MYISAM");
	exe("CREATE TABLE CS_UNIS_MEDS (idCsUniMed CHAR (15) NOT NULL PRIMARY KEY,csUniMed CHAR (150) default '-') ENGINE = MYISAM");
	exe("CREATE TABLE CS_REGS_FISS (idCsRegFis CHAR (15) NOT NULL PRIMARY KEY,csRegFis CHAR (150) default '-') ENGINE = MYISAM");
	exe("CREATE TABLE CS_IMPS (idCsImp CHAR (15) NOT NULL PRIMARY KEY,csImp CHAR (20) default '-') ENGINE = MYISAM");
	exe("CREATE TABLE CS_FORS_PAGS (idCsForPag CHAR (15) NOT NULL PRIMARY KEY,csForPag CHAR (100) default '-') ENGINE = MYISAM");
	
	$SQL="INSERT INTO REGS_FISS (ID_REG_FIS,REG_FIS,ID_CS_REG_FIS,BAJA) VALUES ";
	$SQL.= "('1','-','-','0'), ";
	$SQL.= "('10','General de Ley Personas Morales','601','0'), ";
	$SQL.= "('11','Personas Morales con Fines no Lucrativos','603','0'), ";
	$SQL.= "('12','Sueldos y Salarios e Ingresos Asimilados a Salarios','605','0'), ";
	$SQL.= "('13','Arrendamiento','606','0'), ";
	$SQL.= "('14','Demás ingresos','608','0'), ";
	$SQL.= "('15','Consolidación','609','0'), ";
	$SQL.= "('16','Residentes en el Extranjero sin Establecimiento Permanente en México','610','0'), ";
	$SQL.= "('17','Ingresos por Dividendos (socios y accionistas)','611','0'), ";
	$SQL.= "('18','Personas Físicas con Actividades Empresariales y Profesionales','612','0'), ";
	$SQL.= "('19','Ingresos por intereses','614','0'), ";
	$SQL.= "('20','Sin obligaciones fiscales','616','0'), ";
	$SQL.= "('21','Sociedades Cooperativas de Producción que optan por diferir sus ingresos','620','0'), ";
	$SQL.= "('22','Incorporación Fiscal','621','0'), ";
	$SQL.= "('23','Actividades Agrícolas, Ganaderas, Silvícolas y Pesqueras','622','0'), ";
	$SQL.= "('24','Opcional para Grupos de Sociedades','623','0'), ";
	$SQL.= "('25','Coordinados','624','0'), ";
	$SQL.= "('26','Hidrocarburos','628','0'), ";
	$SQL.= "('27','Régimen de Enajenación o Adquisición de Bienes','607','0'), ";
	$SQL.= "('28','De los Regímenes Fiscales Preferentes y de las Empresas Multinacionales','629','0'), ";
	$SQL.= "('29','Enajenación de acciones en bolsa de valores','630','0'), ";
	$SQL.= "('30','Régimen de los ingresos por obtención de premios','615','0')";
	exe($SQL);
	$SQL="INSERT INTO IMPS (idImp,codigo,imp,tipo,idCsImp,baja) VALUES ";
	$SQL.= "('1','-','-','-','-','0'), ";
	$SQL.= "('10','I16','IVA 16%','IVA','002','0')";
	exe($SQL);
	$SQL="INSERT INTO USUS (idUsu,nom,ape,usu,pass,tel,email,role) VALUES ";
	$SQL.= "('1','-','-','-','-','0','0','USER_ROLE'), ";
	$SQL.= "('10','simpleRestPHP','SRL','master@simpleRestPHP.com','123456','0','master@simpleRestPHP.com','ADMIN_ROLE')";
	exe($SQL);
	$SQL="INSERT INTO USUS_PERS (ID_USU_PER,USU_PER,BAJA) VALUES ";
	$SQL.= "('1','Oper','0'), ";
	$SQL.= "('2','Super','0'), ";
	$SQL.= "('3','Admin','0'), ";
	$SQL.= "('4','Master','0')";
	exe($SQL);
	$SQL="INSERT INTO USUS_ACSS (ID_USU_ACS,ID_USU,ID_MNU_REG,ID_USU_PER) VALUES ";
	$SQL.= "('1','10','1','1'), ";
	$SQL.= "('2','10','2','1'), ";
	$SQL.= "('3','10','3','1'), ";
	$SQL.= "('4','10','4','1'), ";
	$SQL.= "('5','10','5','1'), ";
	$SQL.= "('6','10','6','1'), ";
	$SQL.= "('7','10','7','1'), ";
	$SQL.= "('8','10','8','1'), ";
	$SQL.= "('9','10','9','1'), ";
	$SQL.= "('10','10','10','1'), ";
	$SQL.= "('11','10','11','1'), ";
	$SQL.= "('12','10','12','1'), ";
	$SQL.= "('13','10','13','1'), ";
	$SQL.= "('14','10','14','1'), ";
	$SQL.= "('15','10','15','1'), ";
	$SQL.= "('16','10','16','1'), ";
	$SQL.= "('17','10','17','1'), ";
	$SQL.= "('18','10','18','1'), ";
	$SQL.= "('19','10','19','1'), ";
	$SQL.= "('20','10','20','1'), ";
	$SQL.= "('21','10','21','1')";
	exe($SQL);
	$SQL="INSERT INTO PAISES (idPais,codigo,pais) VALUES ";
	$SQL.= "('1','-','-'), ";
	$SQL.= "('2','AR','ARGENTINA'), ";
	$SQL.= "('3','MX','MEXICO')";
	exe($SQL);
	$SQL="INSERT INTO FONS (idFon,idCsForPag,idMdl,codigo,fon,idMon,baja) VALUES ";
	$SQL.= "('50','1','0','1','Efectivo','MXN','0'), ";
	$SQL.= "('51','2','0','2','Cheque nominativo','MXN','0'), ";
	$SQL.= "('52','3','0','3','Transferencia electrónica de fondos','MXN','0'), ";
	$SQL.= "('53','4','0','4','Tarjeta de crédito','MXN','0'), ";
	$SQL.= "('54','5','0','5','Monedero electrónico','MXN','0'), ";
	$SQL.= "('55','6','0','6','Dinero electrónico','MXN','0'), ";
	$SQL.= "('56','8','0','8','Vales de despensa','MXN','0'), ";
	$SQL.= "('57','12','0','12','Dación en pago','MXN','0'), ";
	$SQL.= "('58','13','0','13','Pago por subrogación','MXN','0'), ";
	$SQL.= "('59','14','0','14','Pago por consignación','MXN','0'), ";
	$SQL.= "('60','15','0','15','Condonación','MXN','0'), ";
	$SQL.= "('61','17','0','17','Compensación','MXN','0'), ";
	$SQL.= "('62','23','0','23','Novación','MXN','0'), ";
	$SQL.= "('63','24','0','24','Confusión','MXN','0'), ";
	$SQL.= "('64','25','0','25','Remisión de deuda','MXN','0'), ";
	$SQL.= "('65','26','0','26','Prescripción o caducidad','MXN','0'), ";
	$SQL.= "('66','27','0','27','A satisfacción del acreedor','MXN','0'), ";
	$SQL.= "('67','28','0','28','Tarjeta de débito','MXN','0'), ";
	$SQL.= "('68','29','0','29','Tarjeta de servicios','MXN','0'), ";
	$SQL.= "('69','30','0','30','Aplicación de anticipos','MXN','0'), ";
	$SQL.= "('70','31','0','31','Intermediario pagos','MXN','0'), ";
	$SQL.= "('71','99','0','99','Por definir','MXN','0')";
	exe($SQL);
	$SQL="INSERT INTO PRZS (idPrz,codigo,prz,baja) VALUES ";
	$SQL.= "('1','-','-','0'), ";
	$SQL.= "('10','2','Aguascalientes','0'), ";
	$SQL.= "('11','3','Baja California','0'), ";
	$SQL.= "('12','4','Baja California Sur','0'), ";
	$SQL.= "('13','5','Campeche','0'), ";
	$SQL.= "('14','6','Chiapas','0'), ";
	$SQL.= "('15','7','Chihuahua','0'), ";
	$SQL.= "('16','8','Ciudad de México','0'), ";
	$SQL.= "('17','9','Coahuila','0'), ";
	$SQL.= "('18','10','Colima','0'), ";
	$SQL.= "('19','11','Durango','0'), ";
	$SQL.= "('20','12','Guanajuato','0'), ";
	$SQL.= "('21','13','Guerrero','0'), ";
	$SQL.= "('22','14','Hidalgo','0'), ";
	$SQL.= "('23','15','Jalisco','0'), ";
	$SQL.= "('24','16','México','0'), ";
	$SQL.= "('25','17','Michoacán','0'), ";
	$SQL.= "('26','18','Morelos','0'), ";
	$SQL.= "('27','19','Nayarit','0'), ";
	$SQL.= "('28','20','Nuevo León','0'), ";
	$SQL.= "('29','21','Oaxaca','0'), ";
	$SQL.= "('30','22','Puebla','0'), ";
	$SQL.= "('31','23','Querétaro','0'), ";
	$SQL.= "('32','24','Quintana Roo','0'), ";
	$SQL.= "('33','25','San Luis Potosí','0'), ";
	$SQL.= "('34','26','Sinaloa','0'), ";
	$SQL.= "('35','27','Sonora','0'), ";
	$SQL.= "('36','28','Tabasco','0'), ";
	$SQL.= "('37','29','Tamaulipas','0'), ";
	$SQL.= "('38','30','Tlaxcala','0'), ";
	$SQL.= "('39','31','Veracruz','0'), ";
	$SQL.= "('40','32','Yucatán','0'), ";
	$SQL.= "('41','33','Zacatecas','0')";
	exe($SQL);
	$SQL="INSERT INTO MENUES (ID_MNU,ID_MNU_REG,NIVEL,ID_MNU_SUP,MNU,MDL,MNU_RUT,MNU_ARC,VIS_RUT,VIS_ICO,ACC) VALUES ";
	$SQL.= "('1','1','1','0','X','-','ini','ini','inicio','home','0'), ";
	$SQL.= "('2','2','1','0','X','-','-','-','-','file','0'), ";
	$SQL.= "('3','3','2','2','X','C','gst','sol_abm','Cotizaciones~Nueva','truck','0'), ";
	$SQL.= "('4','4','2','2','X','S','gst','sol_abm','Solicitudes~Nueva','truck','0'), ";
	$SQL.= "('5','5','2','2','X','-','gst','sol_bus','Solicitudes~Busqueda','truck','0'), ";
	$SQL.= "('6','6','1','0','X','-','-','-','-','gear','0'), ";
	$SQL.= "('7','7','2','6','X','-','cfg','abm_fcps','Conf.~A.B.M. Clientes.','plus','0'), ";
	$SQL.= "('8','8','2','6','X','-','cfg','abm_cces','Conf.~A.B.M. Concecio.','plus','0'), ";
	$SQL.= "('9','9','2','6','X','-','cfg','abm_bcos','Conf.~A.B.M. Bancos.','plus','0'), ";
	$SQL.= "('10','10','2','6','X','P','cfg','abm_przs','Conf.~A.B.M. Provincias.','plus','0'), ";
	$SQL.= "('11','11','2','6','X','Z','cfg','abm_przs','Conf.~A.B.M. Zonas.','plus','0'), ";
	$SQL.= "('12','12','2','6','X','-','cfg','abm_frms','Conf.~A.B.M. Formularios.','plus','0'), ";
	$SQL.= "('13','13','2','6','X','-','cfg','abm_emps','Conf.~A.B.M. Usuarios.','plus','0'), ";
	$SQL.= "('14','14','1','0','X','-','-','-','-','bar-chart','0'), ";
	$SQL.= "('15','15','2','14','X','-','rep','rep_sol','Reportes~Ventas','dollar','0'), ";
	$SQL.= "('16','16','1','0','SYSTEM','-','-','-','-','server','0'), ";
	$SQL.= "('17','17','2','16','A.B.M. Menu','-','cfg','abm_menu','Conf.~A.B.M. Menu.','plus','0'), ";
	$SQL.= "('18','18','2','16','Panel de Control','-','sys','pan_con/pan_con','System~Panel de Control','cogs','0')";
	exe($SQL);
	$SQL="INSERT INTO ARTS (idArt,idUsu,art,codigo,precio,idCsProSrv,idImp,impTasa,idMdl,idUniMed,baja) VALUES ";
	$SQL.= "('1','10','Articulo de prueba','ART1','150','20122004','10','16','7','3','0'), ";
	$SQL.= "('2','10','Sistema de inventarios','SIS_STK','100','43231508','10','16.50','7','2','0'), ";
	$SQL.= "('3','10','Sistema Testing','SIS_TEST','225','43232406','10','16','7','2','0')";
	exe($SQL);
	$SQL="INSERT INTO FCPS (idFcp,idUsu,idMdl ,codigo,nom,ape,fcp,rso,rfc,email,idRegFis,regFis,idFon,fon,tel,fisDom,fisDomNro,fisDomInt,fisDomCodPos,fisDomCol,fisDomMun,fisDomCiu,fisDomIdPrz,fisDomPrz,fisDomIdPais,fisDomPais,envDom,envDomNro,envDomInt,envDomCodPos,envDomCol,envDomMun,envDomCiu,envDomIdPrz,envDomPrz,envDomIdPais,envDomPais,baja) VALUES ";
	$SQL.= "('2','10','2','1','Alex','Otano','Monitores Patunos SA','Monitores Patunos SA','OASA880623Mf1','alex@gmail.com','601','General de Ley Personas Morales','50','Efectivo','1234545','Irene Robledo Garcia','670','D','44230','Santa Elena Estadio','Guadalajara','Guadalajara','23','Jalisco','3','Mexico','Calle','580','D','44230','Narvarte','Ciudad de Mexico','Ciudad de Mexico','23','Jalisco','3','Mexico','0')";
	exe($SQL);
	echo 'TODO OK!';
